name: 'MASS Release Notes Action'
description: 'This action aggregates release notes across several repositories.'
inputs:
  github_token:
    description: 'The GitHub API access token to use for authentication.'
    required: true
  new_server_version:
    description: 'The latest server tag'
    required: true
  release_type:
    description: 'Stable or beta.'
    required: false    
branding:
  icon: 'box'
  color: 'purple'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --github_token=${{ inputs.github_token }}
    - --new_server_version=${{ inputs.new_server_version }}
    - --release_type=${{ inputs.release_type }}
